/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.gradle.multi.web;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
